In [10]:
import numpy as np
import cv2
import re

In [16]:
img = cv2.imread('./images/0021.jpg')


In [17]:
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
# load cascade classifier - frontalface

In [20]:
face_cascade =cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

In [21]:
# apply cascade classifier to an image 
faces, num_detection = face_cascade.detectMultiScale2(img)

In [22]:
print(faces)

[[114  40 196 196]]


In [23]:
# 196 and 196 are width and height of the face

In [24]:
print(num_detection)

[89]


In [25]:
pt1= (114, 40)
pt2 = (114+196,40+196)
# draw the rectangle 

cv2.rectangle(img,pt1,pt2,(255,0,255))
cv2.imshow('face_detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
cx = 114 + 196//2
cy =40 + 196//2
r = 196//2
cv2.circle(img,(cx,cy),r,(0,255,255),2)
cv2.imshow('face_detection_circle',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [27]:
img = cv2.imread('./images/friends.jpg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [28]:
face_cascade =cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

In [38]:
# apply cascade classifier to an image 
# anything greater than 8 or 10 is a good minNeighbour 
faces , num_detecttion = face_cascade.detectMultiScale2(img,minNeighbors =8)
# run a loop
for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,255),3)
    
# display the image 
cv2.imshow('face_detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


print(faces)

[[128 107  96  96]
 [255  90  95  95]
 [407  92  95  95]]


In [35]:
print(num_detecttion)

[104  84  71]


In [39]:
# faces and eye detection

img = cv2.imread('./images/friends.jpg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [40]:
face_cascade =cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_eye.xml')

In [42]:
# step1 : Face Detection
faces, num_detection_face = face_cascade.detectMultiScale2(img,minNeighbors =8)
for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,255),3)
# step2 : eye detection 
    face_roi = img[y:y+h, x:x+h] #cropping the image 
#     step 3: apply cascade classifier (eye)
    eye, num_detection_eyes = eye_cascade.detectMultiScale2(face_roi)
    for ex,ey,ew,eh in eye:
        cx = x + ex+ew//2 
        cy = y + ey+eh//2 
        r =  eh//2 
        cv2.circle(img,(cx,cy),r,(255,255,0),2)
    
# display the image 
cv2.imshow('face_eye_detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()




In [43]:
# face eye smile detection 


In [44]:
img = cv2.imread('./images/friends.jpg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [45]:
face_cascade =cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_eye.xml')
smile_cascade =  cv2.CascadeClassifier('./cascade_classifier/haarcascade_smile.xml')

In [47]:
# step1 : Face Detection
faces, num_detection_face = face_cascade.detectMultiScale2(img,minNeighbors =8)
for x,y,w,h in faces:
    face_roi = img[y:y+h, x:x+h].copy() #cropping the image 
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,255),3)

#     step 2: apply cascade classifier (eye)
    eye, num_detection_eyes = eye_cascade.detectMultiScale2(face_roi)
    for ex,ey,ew,eh in eye:
        cx = x + ex+ew//2 
        cy = y + ey+eh//2 
        r =  eh//2 
        cv2.circle(img,(cx,cy),r,(255,255,0),2)
#   step 3:  smile detection 
    smile, num_detection_smile = smile_cascade.detectMultiScale2(face_roi)
    for sx,sy,sw,sh in smile:
        cv2.rectangle(img,(x+sx,y+sy),(x+sx+sw,y+sy+sh),(255,255,255),2 )
        
    
# step 4 : display the image 
cv2.imshow('face_eye_smile_detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()